# Generated by Django 5.0.2 on 2024-02-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_course_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='month',
        ),
        migrations.AlterField(
            model_name='course',
            name='academicyear',
            field=models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015')], default='2024', max_length=20),
        ),
    ]
