# Generated by Django 5.0.2 on 2024-02-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_course_month_alter_course_academicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('odd', 'ODD'), ('even', 'EVEN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[('2024', '2024th'), ('2023', '2023rd'), ('2022', '2022nd'), ('2021', '2021st'), ('2020', '2020th'), ('2019', '2019th'), ('2018', '2018th'), ('2017', '2017th'), ('2016', '2016th'), ('2015', '2015th')], default='2024'),
        ),
    ]
