# Generated by Django 5.0.2 on 2024-02-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academicyear',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2022-2023', '2022-2023')], max_length=20),
        ),
    ]
