# Generated by Django 5.0.2 on 2024-02-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_course_year_alter_faculty_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('B-Tech', 'B-Tech'), ('M-Tech', 'M-Tech')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('odd', 'ODD'), ('even', 'EVEN')], max_length=10),
        ),
    ]
