# Generated by Django 5.0.2 on 2024-02-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_student_program_alter_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('B-Tech', 'B-Tech'), ('M-Tech', 'M-Tech')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Professor', 'PROFESSOR'), ('Associate Professor', 'ASSOCIATE PROFESSOR')], max_length=50),
        ),
    ]
