# Generated by Django 5.0.2 on 2024-02-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_course_program_alter_faculty_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourseMapping',
            fields=[
                ('mappingid', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty')),
            ],
            options={
                'db_table': 'facultycoursemapping',
            },
        ),
    ]
