# Generated by Django 5.0.2 on 2024-03-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_course_credits_course_ltps'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycoursemapping',
            name='component',
            field=models.CharField(choices=[('L', 'LECTURE'), ('T', 'TUTORIAL'), ('P', 'PRACTICAL'), ('S', 'SKILLING')], default='L', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='section',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='type',
            field=models.BooleanField(default=True, verbose_name='Main Faculty/Not'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.FloatField(default=False, max_length=10, null=True),
        ),
    ]
