# Generated by Django 5.0.2 on 2024-03-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_facultycoursemapping_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
