# Generated by Django 5.0.2 on 2024-04-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_contactus_alter_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='firstname',
            new_name='fn',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='lastname',
            new_name='ln',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='comments',
            new_name='mob',
        ),
        migrations.AddField(
            model_name='contactus',
            name='msg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
