# Generated by Django 5.0.2 on 2024-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='faculty',
            field=models.CharField(max_length=100),
        ),
    ]
