# Generated by Django 5.0.2 on 2024-04-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_rename_firstname_contactus_fn_and_more'),
        ('facultyapp', '0002_alter_coursecontent_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty'),
        ),
    ]
