# Generated by Django 5.0.2 on 2024-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
